# Generated by Django 5.2.11 on 2026-02-12 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Q3 Import Logistics - Asia to US', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Bidding'), ('CLOSED', 'Closed / Awarded'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(help_text='Bidding closes at this time')),
                ('current_round', models.IntegerField(default=1, help_text='Current active bidding round')),
                ('is_public', models.BooleanField(default=False, help_text='If true, any vendor can see it')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('container_type', models.CharField(default='40HC', max_length=50)),
                ('volume', models.IntegerField(default=1, help_text='Number of containers')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='AI Predicted Reference Price', max_digits=10, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='rfqs.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transit_time_days', models.IntegerField(help_text='Estimated days at sea')),
                ('valid_until', models.DateField()),
                ('is_winner', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, help_text='1 = L1 (Best Price)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rfqs.shipment')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
