# Generated by Django 5.2.11 on 2026-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='visible_bids',
            field=models.BooleanField(default=False, help_text="If True, vendors see other vendors' bids"),
        ),
        migrations.AddField(
            model_name='bid',
            name='visible_target_price',
            field=models.BooleanField(default=False, help_text='If True, vendors see the Target Price'),
        ),
    ]
