# Generated by Django 5.2.11 on 2026-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0002_bid_visible_bids_bid_visible_target_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='visible_bids',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='visible_target_price',
        ),
        migrations.AddField(
            model_name='rfq',
            name='visible_bids',
            field=models.BooleanField(default=False, help_text="If True, vendors see other vendors' bids"),
        ),
        migrations.AddField(
            model_name='rfq',
            name='visible_target_price',
            field=models.BooleanField(default=False, help_text='If True, vendors see the Target Price'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='transit_time_days',
            field=models.IntegerField(default=30, help_text='Estimated days at sea'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
