# Generated by Django 5.2.11 on 2026-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_remove_bid_visible_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ai_predicted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal AI Reference', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual Price set by Admin', max_digits=10, null=True),
        ),
    ]
