# Generated by Django 5.2.11 on 2026-02-15 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0004_shipment_ai_predicted_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='free_days_demurrage',
            field=models.IntegerField(default=7, help_text='Free days at destination before charges'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total Freight Cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='transit_time_days',
            field=models.IntegerField(help_text='Estimated days at sea'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='valid_until',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('shipment', 'vendor')},
        ),
    ]
