# Generated by Django 6.0.2 on 2026-02-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0005_bid_free_days_demurrage_alter_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ai_predicted_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bid_docs/'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed instructions for vendors', null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rfq_docs/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='free_days_demurrage',
            field=models.IntegerField(default=14, help_text='Free days at destination'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='visible_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='visible_target_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
