# Generated by Django 6.0.2 on 2026-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0006_alter_bid_options_rename_submitted_at_bid_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bid',
            name='counter_offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='counter_offer_status',
            field=models.CharField(choices=[('NONE', 'No Counter Offer'), ('PENDING', 'Counter Offer Pending'), ('ACCEPTED', 'Counter Offer Accepted'), ('REJECTED', 'Counter Offer Rejected')], default='NONE', max_length=20),
        ),
    ]
