# Generated by Django 6.0.2 on 2026-02-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0007_alter_bid_unique_together_bid_counter_offer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
