# Generated by Django 6.0.2 on 2026-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0008_bid_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. German Supply Chain', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='container_type',
            field=models.CharField(default='40HC', max_length=20),
        ),
    ]
