"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.templatetags.static import static
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(#pq-f$(b_o@j1kn%9im$etcckq=^h3vduvzmoyxh^vv##(w2h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne', # <--- KEEP THIS ONE (Must be at the top)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    # 'daphne', <--- DELETED THIS DUPLICATE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    'rest_framework',
    'corsheaders',
    'channels', # <--- Ensure Channels is here

    # Custom Apps
    'apps.users',
    'apps.rfqs',
    'apps.chat',
    'apps.analytics',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# ...

# REPLACE THE OLD SQLITE DATABASE SECTION WITH THIS:
DATABASES = {
    'default': dj_database_url.config(
        # Replace this string with YOUR Supabase Connection String
        default='postgresql://postgres.bdqdbjmfxiyhmetafybn:4NE5xtTz8zT5bMp8@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import sys
import os

# Allow Django to find the 'apps' folder
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# WebSockets Configuration
ASGI_APPLICATION = "config.asgi.application"

# CORS Settings (Allow Frontend to talk to Backend)
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True

# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

UNFOLD = {
    "SITE_TITLE": "Shipsy Admin",
    "SITE_HEADER": "Shipsy Command",
    "SITE_URL": "/",
    # "SITE_ICON": lambda request: static("logo.svg"),  # optional
    "DASHBOARD_CALLBACK": "apps.analytics.dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247", # Purple brand color
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in sidebar
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Business Core",
                "separator": True,
                "items": [
                    {
                        "title": "RFQs",
                        "icon": "inventory_2", # Google Material Icon
                        "link": reverse_lazy("admin:rfqs_rfq_changelist"),
                    },
                    {
                        "title": "Shipments",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:rfqs_shipment_changelist"),
                    },
                     {
                        "title": "Bids",
                        "icon": "gavel",
                        "link": reverse_lazy("admin:rfqs_bid_changelist"),
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "group",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": "Vendors",
                        "icon": "store",
                        "link": reverse_lazy("admin:users_vendorprofile_changelist"),
                    },
                ],
            },
        ],
    },
}
# Channels Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}