# Generated by Django 5.2.11 on 2026-02-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shipsy Clone', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If True, only Admins can log in')),
                ('allow_new_registrations', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
