import io
from fpdf import FPDF
from django.core.files.base import ContentFile
from django.utils import timezone

class FreightPDF(FPDF):
    def header(self):
        # Logo and Title
        self.set_font("helvetica", "B", 24)
        self.set_text_color(15, 23, 42) # #0f172a
        self.cell(100, 10, "Freight", ln=0)
        self.set_text_color(37, 99, 235) # #2563eb
        self.set_x(36) # Position "OS" right after "Freight"
        self.cell(40, 10, "OS", ln=1)
        
        # Border line
        self.set_draw_color(15, 23, 42)
        self.set_line_width(0.8)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184) # #94a3b8
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.multi_cell(0, 4, "SECURE DIGITAL AGREEMENT\nGenerated by FreightOS Procurement Engine. No physical signature required.\nDocument Hash ID: Generated on Platform", align='C')

def generate_contract_pdf(bid):
    rfq = bid.shipment.rfq
    org = rfq.created_by
    vendor = bid.vendor
    current_date = timezone.now().strftime('%B %d, %Y')
    formatted_amount = f"{bid.amount:,.2f}"

    # Initialize PDF
    pdf = FreightPDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    
    # 1. Document Info (Top Right)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.set_xy(140, 12)
    pdf.cell(60, 5, "DIGITAL FREIGHT AGREEMENT", ln=1, align='R')
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 7, f"REF: BID-{bid.id}-RFQ-{rfq.id}", ln=1, align='R')
    pdf.set_text_color(37, 99, 235)
    pdf.cell(190, 7, f"Executed: {current_date}", ln=1, align='R')
    
    pdf.set_xy(10, 35) # Move back to start
    
    # 2. Parties Section (Boxes)
    pdf.set_fill_color(248, 250, 252) # #f8fafc
    pdf.rect(10, 35, 90, 35, 'F')
    pdf.set_fill_color(239, 246, 255) # #eff6ff
    pdf.rect(110, 35, 90, 35, 'F')
    
    # Shipper Text
    pdf.set_xy(12, 38)
    pdf.set_font("helvetica", "B", 7)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(90, 5, "SHIPPER / AWARDING PARTY", ln=1)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(90, 7, f"{org.company_name or org.username}", ln=1)
    pdf.set_font("helvetica", "", 9)
    pdf.cell(90, 5, f"Contact: {org.email}", ln=1)
    
    # Carrier Text
    pdf.set_xy(112, 38)
    pdf.set_font("helvetica", "B", 7)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(90, 5, "CARRIER / EXECUTING PARTY", ln=1)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(90, 7, f"{vendor.company_name or vendor.username}", ln=1)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(90, 5, f"Contact: {vendor.email}", ln=1)
    
    pdf.ln(15)
    
    # 3. Logistics Overview Table
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 10, "LOGISTICS OVERVIEW", ln=1)
    
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(63, 10, "Transit Time", border=1, fill=True, align='C')
    pdf.cell(63, 10, "Free Days", border=1, fill=True, align='C')
    pdf.cell(64, 10, "Volume", border=1, fill=True, align='C')
    pdf.ln()
    
    pdf.set_font("helvetica", "", 12)
    pdf.cell(63, 12, f"{bid.transit_time_days} Days", border=1, align='C')
    pdf.cell(63, 12, f"{bid.free_days_demurrage} Days", border=1, align='C')
    pdf.cell(64, 12, f"{bid.shipment.volume}x {bid.shipment.container_type}", border=1, align='C')
    pdf.ln(15)
    
    # 4. Routing
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(95, 10, "PORT OF LOADING", ln=0)
    pdf.cell(95, 10, "PORT OF DISCHARGE", ln=1, align='R')
    
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(95, 7, f"{bid.shipment.origin_port}", ln=0)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(95, 7, f"{bid.shipment.destination_port}", ln=1, align='R')
    
    pdf.ln(15)

    # 5. Financials
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 10, "FINANCIAL BREAKDOWN", ln=1)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(140, 10, "Ocean Freight Rate (Door to Door / Port to Port)", border='B')
    pdf.cell(50, 10, "Included", border='B', ln=1, align='R')
    
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_fill_color(248, 250, 252)
    pdf.cell(100, 15, "TOTAL CONTRACT VALUE", fill=True)
    pdf.cell(90, 15, f"{bid.currency} ${formatted_amount}", fill=True, ln=1, align='R')

    # Create the ContentFile for Django
    # Using 'S' dest returns the PDF as a byte string
    pdf_output = pdf.output()
    
    return ContentFile(pdf_output, name=f'FreightOS_Contract_RFQ{rfq.id}_BID{bid.id}.pdf')