import io
from fpdf import FPDF
from django.core.files.base import ContentFile
from django.utils import timezone

class FreightPDF(FPDF):
    def header(self):
        # Logo and Title
        self.set_font("helvetica", "B", 24)
        self.set_text_color(15, 23, 42)  # Dark Slate (#0f172a)
        self.cell(100, 10, "Freight", ln=0)
        
        # Swapped Blue to Vibrant Orange for the "OS" logo accent
        self.set_text_color(249, 115, 22) # Orange 500 (#f97316)
        self.set_x(38) # Adjusted slightly for better kerning
        self.cell(40, 10, "OS", ln=1)
        
        # Border line - changed to a sleek, thinner line
        self.set_draw_color(226, 232, 240) # Light Slate
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(12)

    def footer(self):
        self.set_y(-25)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184) # Slate 400 (#94a3b8)
        self.set_draw_color(226, 232, 240) # Slate 200
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)
        self.multi_cell(0, 4, "SECURE DIGITAL AGREEMENT\nGenerated by FreightOS Procurement Engine. No physical signature required.\nDocument Hash ID: Generated on Platform", align='C')

def generate_contract_pdf(bid):
    rfq = bid.shipment.rfq
    org = rfq.created_by
    vendor = bid.vendor
    current_date = timezone.now().strftime('%B %d, %Y')
    formatted_amount = f"{bid.amount:,.2f}"

    # Initialize PDF
    pdf = FreightPDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    
    # --- 1. Document Info (Top Right) ---
    pdf.set_font("helvetica", "B", 8)
    pdf.set_text_color(100, 116, 139) # Slate 500
    pdf.set_xy(140, 10)
    pdf.cell(60, 5, "DIGITAL FREIGHT AGREEMENT", ln=1, align='R')
    
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(190, 6, f"REF: BID-{bid.id}-RFQ-{rfq.id}", ln=1, align='R')
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(249, 115, 22) # Primary Orange
    pdf.cell(190, 6, f"Executed: {current_date}", ln=1, align='R')
    
    pdf.set_xy(10, 35) # Move back to start of content
    
    # --- 2. Parties Section (Boxes with improved padding) ---
    # Shipper Box (Neutral Light Gray)
    pdf.set_fill_color(248, 250, 252) # Slate 50
    pdf.set_draw_color(226, 232, 240) # Slate 200 border
    pdf.rect(10, 35, 90, 35, 'FD') # 'FD' fills and draws border
    
    # Carrier Box (Soft Orange Tint)
    pdf.set_fill_color(255, 247, 237) # Orange 50 (#fff7ed)
    pdf.set_draw_color(253, 186, 116) # Orange 300 border
    pdf.rect(110, 35, 90, 35, 'FD')
    
    # Shipper Text (Added 5mm padding -> Y=40 instead of 38)
    pdf.set_xy(15, 40)
    pdf.set_font("helvetica", "B", 7)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(80, 5, "SHIPPER / AWARDING PARTY", ln=1)
    pdf.set_x(15)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(80, 7, f"{org.company_name or org.username}", ln=1)
    pdf.set_x(15)
    pdf.set_font("helvetica", "", 9)
    pdf.cell(80, 5, f"Contact: {org.email}", ln=1)
    
    # Carrier Text (Added 5mm padding)
    pdf.set_xy(115, 40)
    pdf.set_font("helvetica", "B", 7)
    pdf.set_text_color(194, 65, 12) # Dark Orange (#c2410c) for headers on orange bg
    pdf.cell(80, 5, "CARRIER / EXECUTING PARTY", ln=1)
    pdf.set_x(115)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(249, 115, 22) # Primary Orange
    pdf.cell(80, 7, f"{vendor.company_name or vendor.username}", ln=1)
    pdf.set_x(115)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(80, 5, f"Contact: {vendor.email}", ln=1)
    
    pdf.ln(20) # Increased spacing after boxes
    
    # --- 3. Logistics Overview Table ---
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "LOGISTICS OVERVIEW", ln=1)
    
    # Table Header (Light Orange)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(255, 237, 213) # Orange 100
    pdf.set_draw_color(253, 186, 116) # Orange 300
    pdf.cell(63, 10, "Transit Time", border=1, fill=True, align='C')
    pdf.cell(63, 10, "Free Days", border=1, fill=True, align='C')
    pdf.cell(64, 10, "Volume", border=1, fill=True, align='C')
    pdf.ln()
    
    # Table Body
    pdf.set_font("helvetica", "", 11)
    pdf.set_fill_color(255, 255, 255)
    pdf.cell(63, 12, f"{bid.transit_time_days} Days", border=1, align='C', fill=True)
    pdf.cell(63, 12, f"{bid.free_days_demurrage} Days", border=1, align='C', fill=True)
    pdf.cell(64, 12, f"{bid.shipment.volume}x {bid.shipment.container_type}", border=1, align='C', fill=True)
    pdf.ln(18)
    
    # --- 4. Routing ---
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(95, 6, "PORT OF LOADING", ln=0)
    pdf.cell(95, 6, "PORT OF DISCHARGE", ln=1, align='R')
    
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(249, 115, 22) # Primary Orange
    pdf.cell(95, 8, f"{bid.shipment.origin_port}", ln=0)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(95, 8, f"{bid.shipment.destination_port}", ln=1, align='R')
    
    # Visual connecting line between ports
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y() + 4, 200, pdf.get_y() + 4)
    pdf.ln(15)

    # --- 5. Financials ---
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "FINANCIAL BREAKDOWN", ln=1)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_draw_color(226, 232, 240)
    pdf.cell(140, 10, "Ocean Freight Rate (Door to Door / Port to Port)", border='B')
    pdf.cell(50, 10, "Included", border='B', ln=1, align='R')
    
    pdf.ln(8)
    
    # Total Box (Highlighted Orange)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_fill_color(255, 247, 237) # Orange 50
    pdf.set_draw_color(253, 186, 116) # Orange 300
    
    # X-offset to center the total box slightly, or keep it full width
    pdf.cell(100, 18, "  TOTAL CONTRACT VALUE", fill=True, border='LTB')
    pdf.set_text_color(249, 115, 22) # Primary Orange
    pdf.cell(90, 18, f"{bid.currency} ${formatted_amount}  ", fill=True, border='RTB', ln=1, align='R')

    # Output
    pdf_output = pdf.output()
    return ContentFile(pdf_output, name=f'FreightOS_Contract_RFQ{rfq.id}_BID{bid.id}.pdf')